### PR TITLE
pull request

### PR DESCRIPTION
**Pull request by e-kwsm**
* create Makefile
* include iostream for separate compilation
* improve has_dot.cpp: use type command

### CODE REVIEW

**Comment by richelbilderbeek** [comment]
Awesome! Thanks!

**Comment by e-kwsm** [comment]
The binary generated by ```make``` is provisionally named ```a.out```; please rename if there is a proper name.

**Comment by richelbilderbeek** [comment]
I want to add you in the (new) acknowledgements section. Now it is `E Kawashima`, but reply if you have a better suggestion.

**Comment by e-kwsm** [comment]
It's OK. Thank you.

**Pull request merged**
